### ISSUE TITLE
Remove content from "The .bashrc file"

### ISSUE THREAD

**Issue by dmtooke-imm** [OBDS-Training/Help#102]
Hi,

I recommend removing the following two sections:

- Interactive sessions (this is rather advanced for casual users and can break stuff)
- File permissions (this should not be needed at all as they're correctly set by the system and can mess up your permissions)
- Modules (this will produce output and break X2Go sessions)

**Comment by kevinrue** [comment]
Can you please link to the relevant pages (either on the deployed website at https://obds-training.github.io/Help/ or the source code at https://github.com/OBDS-Training/Help)

Because I'm not clear which page you refer to as 'interactive sessions'.

Thanks!

**Comment by kevinrue** [comment]
OK, I found it among a few hits using the search bar:

https://obds-training.github.io/Help/docs/linux/profile-and-configuration/bashrc/#interactive-sessions

**Comment by kevinrue** [comment]
- Interactive session: goes to an advanced section elsewhere (TBD)
- File permission: remove
- Modules: add caveat about any output message breaking X2Go

**Comment by kevinrue** [comment]
Looking at it now again (was about to work on other pages in that general section), I've got questions about how you picture the changes.

My focus right now is your point about interactive sessions.

I understand you want to remove the section titled 'Interactive sessions' from this page (with David we discussed how we'd like to move it to another page of 'advanced' topics).
However, I assume that means also removing the `if [[ $PS1 ]]; then` line from the template contents in the 'Contents' section on the same page.
In that case, you'll need to clarify one more thing: I would keep the contents within that `if` block in the template, simply de-indenting it. Is that what you had in mind, or you wanted me to remove _all_ the contents in the `if PS1` block?

I know it would be asking a bit more work from you, but it would really help if in the future you could make a pull request (i.e., fork the repo, commit a few changes, and open a PR to this repo) to illustrate your suggestions more precisely. "A pull request is worth a thousand words" kind of logic at play here :)

I wish I could say that a more detailed description of the changes would help, but that would just be kicking the can down the road until a PR is needed anyway.
