### ISSUE TITLE
Suggested changes to https://obds-training.github.io/Help/docs/connect/ssh-configuration/ssh-key-pair/

### ISSUE THREAD

**Issue by dmtooke-imm** [OBDS-Training/Help#121]
- Please change the SSH key generation algorithm to "ssh-keygen -t ecdsa -b 521". 
- Please change the text to say that a 16 character private key password is mandatory and the private keys without a password are strictly prohibited
- Please update copying the public file command to "ssh-copy-id -i ~/.ssh/ecdsa <username>@<remote>" (I think)
- Please change the SSH config line to "IdentityFile ~/.ssh/ecdsa"
- Please remove all config lines after this (let's chat this over at some point)#
- Please update the section "Login with your SSH keypair" to "You can now log into the CCB cluster using the same ssh command as before. You will be prompted to type your SSH passphrase when the SSH key pair is used."

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by kevinrue** [comment]
Revisited this in #169 
Namely, I've moved the extra ssh config options to a separate page "advanced client configuration" with a clear warning that we don't recommend using those options unless the need is identified.
