### ISSUE TITLE
Suggested addition to https://obds-training.github.io/Help/docs/linux/processes/hangup/

### ISSUE THREAD

**Issue by dmtooke-imm** [OBDS-Training/Help#126]
We should add a section on terminal multiplexers, especially "tmux".

We could also add a section on "screen" and using Emacs as a daemon if desired. I'm happy to help with the content on these and could easily provide the cheatsheet list of basic commands.

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by kevinrue** [comment]
Closed by #189 (tmux and emacs daemon added).

We agreed that with `tmux` covered, there is little point adding anything about `screen`.
