### ISSUE TITLE
Suggested change to https://obds-training.github.io/Help/docs/linux/modules/introduction/

### ISSUE THREAD

**Issue by dmtooke-imm** [OBDS-Training/Help#127]
- Please add "module purge"
- We should discuss a possible location for the content in https://datashare.molbiol.ox.ac.uk/public/man/man7/python-cbrg.7.html and https://datashare.molbiol.ox.ac.uk/public/man/man7/R-cbrg.7.html

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by kevinrue** [comment]
Closed by #190 #191 #192
