### ISSUE TITLE
Suggested change to https://obds-training.github.io/Help/docs/help/contact/

### ISSUE THREAD

**Issue by dmtooke-imm** [OBDS-Training/Help#131]
- Please could we have a contact address for OBDS and training questions

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by dmtooke-imm** [comment]
Not stale

**Comment by kevinrue** [comment]
Just went through the setup with Simon. Waiting to see whether the new account shows up automatically in my Outlook in the next few days; otherwise I'll investigate further whether I need to do any manual step myself.

Need to talk about it with @david-cgat at the next opportunity

**Comment by kevinrue** [comment]
Not completed. Email exists but not advertised yet, pending definition of the scope it is responsible for.

**Comment by dmtooke-imm** [comment]
Not stale
